### ISSUE TITLE
Username attribute in one of the condition

### ISSUE THREAD

**Issue by surajtikoo** [clouddrove/terraform-aws-sftp#22] opened 2023-09-01 13:33 UTC
user_names = length(var.sftp_users) > 0 ? [for user in var.sftp_users : user.username] : []

Here the username should be user_name

**Comment by anmolnagpal** [comment] 2023-09-04 00:10
@surajtikoo would be great if you could create a pull request for the same!

**Comment by pendharevaibhav-cd** [comment] 2023-09-04 10:47
Hello @surajtikoo, I appreciate your contribution and taking the time to report the issue in our GitHub repository. After reviewing your code changes, I noticed that everything looked good overall. However, I did identify a few minor adjustments that were missed. I've gone ahead and made those necessary changes, and I've successfully merged the code into the new release tagged as `1.3.1`. The issue is now resolved, and I'm closing it. Thank you again for your contribution!

**Closed as completed by pendharevaibhav-cd** 2023-09-04 10:47 UTC
Labels: bug
